%macro CreateSources(dirPath, libraryname, catname, modulename);

	libname &libraryname "&dirPath";
	filename src_cat catalog "&libraryname..&catname..&modulename..source";
	filename mydata "&dirPath.\&modulename..sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;
	filename src_cat catalog "&libraryname..&catname..&modulename._create.source";
	filename mydata "&dirPath.\&modulename._create.sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;
	filename src_cat catalog "&libraryname..&catname..&modulename._train.source";
	filename mydata "&dirPath.\&modulename._train.sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;
	filename src_cat catalog "&libraryname..&catname..&modulename._score.source";
	filename mydata "&dirPath.\&modulename._score.sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;
	filename src_cat catalog "&libraryname..&catname..&modulename._report.source";
	filename mydata "&dirPath.\&modulename._report.sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;

    filename src_cat catalog "&libraryname..&catname..random_matrices.source";
	filename mydata "&dirPath.\random_matrices.sas";
	data _null_;
		file src_cat;
		infile mydata;
		input;
		put _infile_;
	run;

	proc catalog cat=&libraryname..&catname.;
		copy out=sashelp.&libraryname.;
	run;
%mend CreateSources;

%CreateSources(C:\Users\sas\Desktop\DPP\DPP\BetaFull\DPP, DPP, BTFLL, BetaFullSampler);
LIBNAME DPP CLEAR;
%CreateSources(C:\Users\sas\Desktop\DPP\DPP\BetaBand\DPP, DPP, BTBND, BetaBandSampler);
LIBNAME DPP CLEAR;
